\documentclass[journal=jacsat,manuscript=article]{achemso}

\usepackage{chemformula} % Formula subscripts using \ch{}
\usepackage[T1]{fontenc} % Use modern font encodings

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% If issues arise when submitting your manuscript, you may want to
%% un-comment the next line.  This provides information on the
%% version of every file you have used.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%\listfiles

\newcommand*\mycommand[1]{\texttt{\emph{#1}}}

\author{Laurent Gatto}
\email{laurent.gatto@uclouvain.be}
\affiliation[UCLouvain]{de Duve Institute, Universit\'e catholique de Louvain, Brussels, Belgium}
\author{Sebastian Gibb}
\affiliation[University of Greifswald]{Department of Anaesthesiology and Intensive Care of the University Medicine Greifswald, Germany}
\author{Johannes Rainer}
\affiliation[EURAC]{Institute for Biomedicine, Eurac Research, Affiliated Institute of the University of L\"ubeck, Bolzano, Italy}


\title[MSnbase version 2]
  {\texttt{MSnbase}, efficient R-based access and manipulation of raw mass spectrometry data}

\abbreviations{}
\keywords{Bioconductor, mass spectrometry, software, reproducible research} %% up to 10 keywords

\begin{document}

%% \begin{tocentry}
%% See achemso-demo.tex
%% \end{tocentry}

\begin{abstract} %% 200 words max
  We present version 2 of the \texttt{MSnbase} R/Bioconductor
  package. \texttt{MSnbase} provides infrastructure for the
  manipulation, processing and visualisation of mass spectrometry
  data. Here we present how the new \textit{on disk} infrastructure
  allows the handling of hundreds on commodity hardware and present
  some application of the package.
\end{abstract}


\section{Introduction}

Mass spectrometry is a powerful technology to assay chemical and
biological samples. It is used routinely, with well characterised
protocols, as well a development platform, to improve on existing
methods and devise new ones to analyse ever more complex sample in
greater details. The complexity and diversity of mass spectrometry
yields data that is itself complex and often times of considerable
size, requiring non trivial processing before producing interpretable
results. This is particularly relevant, and can constitue a
significant challenge for method developers that, in addition to the
development of sample processing and mass spectrometry methods, need
to process and analyse these new data to demonstrate the improvement
in their technical and analytical work.


There exists a very diverse catalogue of software tools to explore,
process and interpret mass spectrometry data. These range from low
level software libraries such as vendor libraries, jmzML (ref),
proteowizard (ref), ... that are aimed at programmers to develop new
applications, to user-oriented applications, such as
ProteomeDiscoverer, MaxQuant, ... that provide a limited and fixed set
of functionality. The former are used through application programming
interfaces exclusively, while the latter generally featuring graphical
user interfaces (GUI).

TODO: Give examples of libraries re-used in user/gui focused
application...


In this software note, we present version 2 of the \texttt{MSnbase}
\cite{Gatto:2012} R/Bioconductor software package. \texttt{MSnbase}
offers a platform that lies between low level libraries and end-use
software. It provides a flexible and interactive command line
environment for metabolomics and proteomics mass spectrometry-based
application. It allows a detailed step-by-step processing, analysis
and exploration of the data and development of novel computational
mass spectrometry methods.


\section{Software functionality}

We are going to present the new raw data infrastructure that has been
available since \texttt{MSnbase} version 2.0, and then describe how it
is leveraged to process large amount of data. We are then going to
demonstrate some visualisation that make use of the raw data
structures available in \texttt{MSnbase} and conlude with an example
if flexible prototyping, by showing how to quickly combine spectra
acquired using the Boxcar method \cite{Meier:2018}.

\subsection{On disk backend}

Efficient low level access: in memory vs on disk mode (using mzR),
benchmarking, used in ms-based proteomics and metabolomics.

\subsection{Use cases}

Example applications:

- large scale data analyses (metabolomics, Johannes)

- visualisation: Jo's XIC plots, possibly also MSMap, with animation.

- boxcar prototyping

\section{Discussion}

To address (from guidelines):

\begin{itemize}

\item{potential for reuse}: see
  \cite{Wieczorek:2017,Griss:2019,Smith:2006} for examples.
\item{general limitations}
\item{system limitations}
\item{end-user documentation}
\item{developer documentation}
\item{sample data}
\item{benchmark data set}
\item{availability}
\item{license information}
\item{system requirements}

\end{itemize}

Collaborative development, 11 contributors since creation (see blog
post).

Count packages depending on \texttt{MSnbase}.

Future developments.

The version of \texttt{MSnbase} used in this manuscritp is version
\Sexpr{packageVersion("MSnbase")}. The main features presented here
were available since version 2.0. 



\begin{acknowledgement}

The authors thank the various contributors and users who have provided
constructuve input and feedback that have helped, over the years, the
improvement of the package. The authors declare no conflict of
interest.

\end{acknowledgement}



%% \begin{suppinfo} %% Supporting Information
%%
%% A listing of the contents of each file supplied as Supporting Information
%% should be included. For instructions on what should be included in the
%% Supporting Information as well as how to prepare this material for
%% publications, refer to the journal's Instructions for Authors.
%%
%% The following files are available free of charge.
%% \begin{itemize}
%%   \item Filename: brief description
%%   \item Filename: brief description
%% \end{itemize}
%% \end{suppinfo}


\bibliography{refs}

\end{document}
